### ISSUE TITLE
Firefox Add-on Button is Broken

### ISSUE THREAD

**Issue by TheMasterOfMadness** [mh-community-tools/mh-helper-extension#107]
The Firefox Add-on button on the main page is broken.

**Comment by tsitu** [comment]
Do you have a screenshot of this? It works fine on my end.

**Comment by TheMasterOfMadness** [comment]
![image](https://user-images.githubusercontent.com/39934989/97213358-84ede700-17e7-11eb-8d48-888d2b3bf67b.png)

**Comment by TheMasterOfMadness** [comment]
The button is linked to : https://addons.mozilla.org/en-US/firefox/addon/jacks-mousehunt-helper/
Whereas, it should be linked to : https://addons.mozilla.org/en-US/firefox/addon/mhct-mousehunt-helper/

**Comment by tsitu** [comment]
Which button are you referring to exactly? The one on the main page was fixed 9 months ago as per https://github.com/mh-community-tools/mh-hunt-helper/commit/ef55bd6d1c0073b0c517a2ca7833240fc7e9637e

**Comment by TheMasterOfMadness** [comment]
The Firefox one on this page.
https://github.com/mh-community-tools/mh-helper-extension

**Comment by tsitu** [comment]
Thanks for clarifying! This has been fixed in #108
