### ISSUE TITLE
loot names containing commas with following spaces break stuff

### ISSUE THREAD

**Issue by DevJackSmith** [mh-community-tools/mh-helper-extension#54]
example: "Deep, Deep, Deep egg" breaks because it tries to separate on `, `
Need to figure out another way of doing it, or just make exception cases for this.

**Comment by AardWolf** [comment]
Could look at the loot string and find if 3 or more items were dropped:

- \d+ would match 3 or more times, 
- " and " would be present, 
- ", \d" would be present.

This regex uses lookaheads in a list of three or more items to return the number, the item, and the ", " at the end, which can be stripped off:
```
(\d+.*?, (?=\d+))|(\d+.* and \d+.*)
```
The last match item in the array has two items separated by " and ".

For two items being dropped we can look for " and \d+", use the index of that, and get two loot strings regardless of commas.

The last case should be a single item being dropped and we don't care about commas.

**Comment by AardWolf** [comment]
An actual string we're working with:

```
"text": "I sounded the Hunter's Horn and was successful in the hunt! I caught a 10 oz. <a href=\"https:\/\/www.mousehuntgame.com\/\" onclick=\"javascript:hg.views.MouseView.show('elite_guardian'); return false;\">Elite Guardian Mouse<\/a> worth 25,500 points and 4,205 gold.<br \/><br \/><b>The mouse also dropped the following loot:<\/b><br \/>1 <a class=\"loot\" title=\"\" href=\"https:\/\/www.mousehuntgame.com\/item.php?item_type=cave_nightshade_crafting_item\" onclick=\"hg.views.ItemView.show('cave_nightshade_crafting_item'); return false;\">Nightshade<\/a>, and 2 <a class=\"loot\" title=\"\" href=\"https:\/\/www.mousehuntgame.com\/item.php?item_type=oxygen_stat_item\" onclick=\"hg.views.ItemView.show('oxygen_stat_item'); return false;\">Oxygen Canisters<\/a>"
```

**Comment by DevJackSmith** [comment]
we now separate the items by using <a> link and get loot item_id and plural name from another part of response object
