### ISSUE TITLE
Perform crown snapshot when clicking own shield

### ISSUE THREAD

**Issue by tehhowch** [mh-community-tools/mh-helper-extension#82]
Prior to the 2020.01.28 patch, clicking the shield always resulted in a page navigation.
On all page navigations, the extension reloads itself, and in doing so will send a POST to the `profiletabs?action=badges` endpoint, at which time the normal XHR listener sees the crown response and submits the snapshot.

Now, however, a full page navigation isn't done when the logged-in user clicks their own shield. As such, the extension doesn't reload and the user's crowns don't get snapshotted. The app route, however, does update.

Solutions:
 - Watch for window.location changes, when the `profile_RE` matches, send the request as though we had reloaded the extension
 - Add a listener to page.php POSTs where the payload page is `HunterProfile`
   - Inspect the response to see if the `tabs` property has a property `kings_crowns` (or if ever an array, that the item's `type` is `"kings_crowns"`). If this "kings_crowns" object exists, then we check if it is initialized; if not, we post (as above). If the tab is initialized, we can access the crown counts via the `"subtabs[0].mouse_crowns.badge_groups"` property chain:
![image](https://user-images.githubusercontent.com/20871346/73413002-220b0600-42d0-11ea-89b1-48da0054acc2.png)

User workarounds: click the shield, then refresh the page

**Comment by AardWolf** [comment]
My digging, maybe it helps someone else...

 in the listener? Gotta be something like: `(url.includes("/managers/ajax/pages/page.php") && xhr.responseJSON.page.tabs.kings_crowns)`
might want to click around on the profile - it's possible that kings_crown tab exists even if the subtabs[0] isn't populated

`process xhr.responseJSON.page.tabs.kings_crowns.subtabs[0].mouse_crowns.badge_groups as though they were xhr.responseJSON.badges`

We discussed this around here: https://discordapp.com/channels/275500976662773761/355474934601875457/673992965789843488

There are pictures.

**Comment by tsitu** [comment]
Should be fixed in a6a277337522296681f5688ffd800c6f7e7b6d9d
