### ISSUE TITLE
Add augments for valour rift

### ISSUE THREAD

**Issue by AardWolf** [mh-community-tools/mh-helper-extension#84]
addValourRiftHuntDetails

user.enviroment_atts.active_augmentations
hr: true
sr: true
ss: true
sste: true
tu: true

(elixir rain missing but we could just use the codenames) - elixir rain is the only one I don't have turned on.

Elixir rain and maybe tu (which I believe is ultimate umbra).

**Comment by tsitu** [comment]
https://discordapp.com/channels/275500976662773761/355474934601875457/634678522027180034

https://github.com/mh-community-tools/mh-helper-extension/blob/master/src/scripts/main.js#L1903

**Comment by DevJackSmith** [comment]
please use full words instead of abbreviations, so it's easier on others.

**Comment by tsitu** [comment]
I think we can close this until there's a strong use case for tracking augments.
